# Generated by Django 6.0.7 on 2026-07-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly installment amount for one_time_installments projects', max_digits=14, null=True),
        ),
    ]
