# Generated by Django 6.0.7 on 2026-07-08 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_installment_amount_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivableinstallment',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_installments', to='api.project'),
        ),
    ]
