# Generated by Django 6.0.7 on 2026-07-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_advance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableinstallment',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('stuck', 'Stuck')], default='ongoing', max_length=15),
        ),
    ]
