# Generated by Django 6.0.7 on 2026-07-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_household_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('contribution', 'Contribution')], default='expense', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, default='', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='householdexpense',
            index=models.Index(fields=['ledger', '-date'], name='hh_exp_ledger_date_idx'),
        ),
        migrations.AddField(
            model_name='householdnotification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='householdnotification',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.householdcontribution'),
        ),
        migrations.AddField(
            model_name='householdnotification',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.householdexpense'),
        ),
        migrations.AddField(
            model_name='householdnotification',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.household'),
        ),
        migrations.AddField(
            model_name='householdnotification',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.householdledger'),
        ),
        migrations.AddField(
            model_name='householdnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='householdnotification',
            index=models.Index(fields=['user', '-created_at'], name='hh_notif_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='householdnotification',
            index=models.Index(fields=['user', 'read_at'], name='hh_notif_user_read_idx'),
        ),
    ]
