# Generated by Django 6.0.7 on 2026-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_household_phase6_polish'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdexpense',
            name='pot_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
