# Generated by Django 6.0.7 on 2026-07-30 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_status_stuck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('remind_payables', models.BooleanField(default=True)),
                ('remind_receivables', models.BooleanField(default=True)),
                ('lead_3', models.BooleanField(default=True)),
                ('lead_1', models.BooleanField(default=True)),
                ('lead_due', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='device_token_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('token',), name='uniq_device_push_token')],
            },
        ),
        migrations.CreateModel(
            name='PushDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payable', 'Payable'), ('receivable', 'Receivable'), ('expense', 'Expense')], max_length=16)),
                ('object_id', models.PositiveIntegerField()),
                ('lead_days', models.PositiveSmallIntegerField(default=0)),
                ('notify_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['notify_date'], name='push_log_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'object_id', 'lead_days', 'notify_date'), name='uniq_push_delivery_day')],
            },
        ),
    ]
