# Generated by Django 6.0.7 on 2026-08-01 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ops_phase0_audit_user_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='marketing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=400)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('audience', models.CharField(choices=[('all', 'All opted-in users with a device'), ('android', 'Android only'), ('inactive_7d', 'Inactive 7d+'), ('inactive_30d', 'Inactive 30d+'), ('inactive_90d', 'Inactive 90d+')], default='all', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_estimate', models.PositiveIntegerField(default=0)),
                ('sent_ok', models.PositiveIntegerField(default=0)),
                ('sent_failed', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushCampaignDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Ok'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('expo_ticket_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.pushcampaign')),
                ('device_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_deliveries', to='api.devicetoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='push_camp_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='pushcampaigndelivery',
            index=models.Index(fields=['campaign', 'status'], name='push_deliv_camp_status_idx'),
        ),
    ]
