# Generated by Django 6.0.7 on 2026-08-06 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ops_phase3_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRemoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=32, unique=True)),
                ('ads_enabled', models.BooleanField(default=True)),
                ('banner_enabled', models.BooleanField(default=True)),
                ('interstitial_enabled', models.BooleanField(default=False)),
                ('rewarded_enabled', models.BooleanField(default=False)),
                ('premium_hides_ads', models.BooleanField(default=True)),
                ('android_banner_unit', models.CharField(blank=True, default='', max_length=128)),
                ('android_interstitial_unit', models.CharField(blank=True, default='', max_length=128)),
                ('android_rewarded_unit', models.CharField(blank=True, default='', max_length=128)),
                ('show_after_sessions', models.PositiveIntegerField(default=3)),
                ('interstitial_min_interval_sec', models.PositiveIntegerField(default=180)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('test_device_ids', models.JSONField(blank=True, default=list)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('min_supported_version', models.CharField(blank=True, default='', max_length=32)),
                ('store_url', models.URLField(blank=True, default='')),
                ('maintenance_message', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App remote config',
                'verbose_name_plural': 'App remote config',
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(choices=[('premium_monthly', 'Premium monthly'), ('premium_yearly', 'Premium yearly'), ('premium_lifetime', 'Premium lifetime')], default='premium_monthly', max_length=64)),
                ('source', models.CharField(choices=[('play', 'Google Play'), ('manual_grant', 'Manual grant'), ('promo', 'Promo')], default='manual_grant', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending verification')], db_index=True, default='active', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('order_id', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('purchase_token_hash', models.CharField(db_index=True, max_length=64)),
                ('order_id', models.CharField(blank=True, default='', max_length=128)),
                ('package_name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], db_index=True, default='received', max_length=16)),
                ('raw_summary', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_events', to='api.entitlement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['user', 'status'], name='entitlement_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['status', 'expires_at'], name='entitlement_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseevent',
            index=models.Index(fields=['status', '-created_at'], name='purchase_evt_status_idx'),
        ),
    ]
