# Generated by Django 6.0.7 on 2026-08-12 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_source',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('manual', 'Manual'), ('cached', 'Cached'), ('offline', 'Offline')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='people_action',
            field=models.CharField(blank=True, choices=[('lend', 'Lend'), ('borrow', 'Borrow'), ('pay', 'Pay'), ('receive', 'Receive')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='people_pair_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('person', 'Person')], default='bank', max_length=10),
        ),
        migrations.CreateModel(
            name='FxRateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=10)),
                ('quote', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'FX rate cache',
                'verbose_name_plural': 'FX rate cache',
                'indexes': [models.Index(fields=['base', 'quote'], name='fx_base_quote_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'quote'), name='uniq_fx_base_quote')],
            },
        ),
        migrations.CreateModel(
            name='TravelMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('travel_currency', models.CharField(blank=True, default='', max_length=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rate_as_of', models.DateTimeField(blank=True, null=True)),
                ('rate_source', models.CharField(blank=True, choices=[('live', 'Live'), ('manual', 'Manual'), ('cached', 'Cached'), ('offline', 'Offline')], default='', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_mode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel mode',
                'verbose_name_plural': 'Travel modes',
            },
        ),
    ]
