# Generated by Django 6.0.7 on 2026-08-12 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_travel_people_phase_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='people_link_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PeopleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('invited_via', models.CharField(choices=[('query', 'Email or username'), ('code', 'Link code')], default='query', max_length=10)),
                ('query_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeopleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('unlinked', 'Unlinked')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='api.peopleinvitation')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_link_as_a', to='api.account')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_link_as_b', to='api.account')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_links_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_links_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeopleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('lend', 'Lend'), ('borrow', 'Borrow'), ('pay', 'Pay'), ('receive', 'Receive')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('people_pair_id', models.CharField(db_index=True, max_length=64)),
                ('client_mutation_id', models.CharField(blank=True, default='', max_length=64)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('original_currency', models.CharField(blank=True, default='', max_length=10)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('fx_source', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_proposals_received', to=settings.AUTH_USER_MODEL)),
                ('counterparty_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_proposals_as_counterparty_wallet', to='api.account')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='api.peoplelink')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_proposals_sent', to=settings.AUTH_USER_MODEL)),
                ('proposer_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people_proposals_as_proposer_wallet', to='api.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeopleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('link_invite', 'Link invite'), ('link_accepted', 'Link accepted'), ('link_declined', 'Link declined'), ('proposal', 'Proposal'), ('proposal_accepted', 'Proposal accepted'), ('proposal_declined', 'Proposal declined')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, default='', max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_notifications_acted', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.peopleinvitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_notifications', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.peopleproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='peopleinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_user'), name='uniq_pending_people_invitation_pair'),
        ),
        migrations.AddConstraint(
            model_name='peoplelink',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user_a', 'user_b'), name='uniq_active_people_link_pair'),
        ),
    ]
