import { useEffect, useState } from 'react'
import './screenshots.css'
import './reference-sections.css'
import './brand.css'

const icons = {
  arrow: <><path d="M5 12h14M13 6l6 6-6 6" /></>,
  play: <path d="m9 7 7 5-7 5V7Z" fill="currentColor" stroke="none" />,
  wallet: <><path d="M4 7.5h15a1 1 0 0 1 1 1V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a3 3 0 0 1 3-3h11" /><path d="M16 13h.01" /></>,
  chart: <><path d="M4 19V5M4 19h16" /><path d="m7 15 4-5 3 2 5-7" /></>,
  bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></>,
  users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75" /></>,
  lock: <><rect width="14" height="11" x="5" y="10" rx="2" /><path d="M8 10V7a4 4 0 0 1 8 0v3" /></>,
  cloud: <path d="M17.5 19H9a7 7 0 1 1 6.71-9.01A5 5 0 1 1 17.5 19Z" />,
  plus: <><path d="M12 5v14M5 12h14" /></>,
  close: <><path d="m6 6 12 12M18 6 6 18" /></>,
}
const Icon = ({ name, size = 20 }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{icons[name]}</svg>
const Reveal = ({ children, className = '' }) => <div className={`reveal ${className}`}>{children}</div>
const Logo = ({ inverse = false }) => <a className={`logo ${inverse ? 'logo--inverse' : ''}`} href="#home"><img src="/media/wallettrail-logo.png" alt="WalletTrails" /><span>Wallet<span>Trails</span></span></a>

const productFeatures = [
  ['wallet', 'All your wallets', 'Bring bank accounts and cash wallets into one simple total.', 'blue'],
  ['chart', 'Monthly reports & forecast', 'Compare expected and actual money, then understand spending by category.', 'purple'],
  ['bell', 'Bill & installment reminders', 'Track monthly costs, loans, and money owed to you before a due date sneaks up.', 'orange'],
  ['users', 'Household sharing', 'Create a private family ledger, invite people, and see shared costs together.', 'green'],
  ['lock', 'Privacy lock', 'Hide amounts in public, then reveal them with your device biometrics or PIN.', 'gold'],
  ['cloud', 'Works offline', 'Add personal income, expenses, and transfers without data; they sync when you are back.', 'coral'],
  ['chart', 'Income that fits your work', 'Record salary, recurring work, one-time jobs, advances, and payments received in parts.', 'blue'],
  ['wallet', 'Transfers without double counting', 'Move money between your own wallets while keeping your overall total correct.', 'purple'],
  ['users', 'Fair split suggestions', 'For shared trips and events, see contributions, who paid, and who owes whom.', 'green'],
  ['bell', 'Local & push notifications', 'Choose reminder lead times for bills; privacy mode keeps exact amounts out of alerts.', 'orange'],
  ['cloud', 'Exports when you need them', 'Share personal and household reports as CSV, with PDF reporting available on web.', 'coral'],
  ['lock', 'Themes and amount controls', 'Choose a look you like while keeping money values under your control.', 'gold'],
]

function PhonePreview() {
  return <div className="phone phone--real-screenshot" aria-label="WalletTrails reports screen preview"><div className="notch" /><img src="/media/screenshots/reports.png" alt="WalletTrails reports screen" /></div>
}

function Header({ menu, setMenu }) {
  return <header className="site-header"><Logo /><button className="hamburger" onClick={() => setMenu(!menu)} aria-label="Open navigation" aria-expanded={menu}><i /><i /><i /></button><nav className={menu ? 'site-nav open' : 'site-nav'}>{[['home', 'Home'], ['screenshots', 'Screenshots'], ['features', 'Features'], ['about', 'About'], ['how', 'How it works'], ['faqs', 'FAQs'], ['support', 'Support']].map(([id, label]) => <a href={`#${id}`} key={id} onClick={() => setMenu(false)}>{label}</a>)}</nav><a className="button compact" href="#download">Get the app <Icon name="arrow" size={16} /></a></header>
}

function ProductDepth() {
  const blocks = [
    ['01 · EARN & PLAN', 'Know what is coming in.', 'Add a salary, a monthly client, a one-time payment, or a job paid in parts. Record an advance and keep the remaining amount in view.', ['Recurring and one-time income', 'Payment-in-parts tracking', 'Received, paused, and complete states'], 'income'],
    ['02 · STAY AHEAD', 'Give due dates a calm place to live.', 'Monthly costs, loan installments, and money people owe you are all visible in one bills space—so your monthly forecast is not a surprise.', ['Due-soon cues and scheduled reminders', 'Payables, receivables, and recurring costs', 'Privacy-safe notification wording'], 'bills'],
    ['03 · SHARE FAIRLY', 'Keep shared money separate—and clear.', 'Personal wallets stay yours. A Household gives family, roommates, or trip groups a shared expense book with member reports and equal-split suggestions.', ['Invite by secure code or shareable link', 'Ongoing home and closeable event ledgers', 'Contributions, settlement suggestions, and reports'], 'family'],
  ]
  return <section className="product-depth"><div className="shell"><Reveal className="heading center"><span className="eyebrow">Built around real money life</span><h2>One app for the details<br />that keep life <em>moving.</em></h2><p>WalletTrails is designed around real Pakistan-first routines—from salary day and a client payment to a family grocery run or a trip with friends.</p></Reveal><div className="depth-grid">{blocks.map(([tag, title, body, points, tone]) => <Reveal className={`depth-card depth-card--${tone}`} key={tag}><small>{tag}</small><h3>{title}</h3><p>{body}</p><ul>{points.map((point) => <li key={point}>{point}</li>)}</ul></Reveal>)}</div><Reveal className="privacy-promise"><span className="ficon gold"><Icon name="lock" size={22} /></span><div><small>OUR PRIVACY PROMISE</small><h3>Your personal wallets stay personal.</h3><p>People in a Household can see only the shared ledger—not each other’s bank wallets, income, loans, or unrelated transactions. Your values can also be hidden on-screen when you need privacy.</p></div><a href="/privacy.html">Read privacy policy <Icon name="arrow" size={16} /></a></Reveal></div></section>
}

const screenshots = [
  ['/media/screenshots/wallet-overview.png', 'Income', 'Income sources, salary, and client payments'],
  ['/media/screenshots/wallets.png', 'Wallets', 'Your cash and bank accounts together'],
  ['/media/screenshots/income.png', 'Everyday money', 'A clear view of the details that matter'],
  ['/media/screenshots/bills.png', 'Bills', 'Monthly costs, loans, and due dates'],
  ['/media/screenshots/reports.png', 'Reports', 'Your month, explained in one place'],
  ['/media/screenshots/household.png', 'Household', 'A shared space for family spending'],
]
function ScreenshotGallery() {
  return <section className="screenshots" id="screenshots"><div className="shell"><Reveal className="heading center"><span className="eyebrow">The real app</span><h2>Designed for the moments<br />when you need <em>clarity.</em></h2><p>Explore WalletTrails across income, wallets, bills, reports, and shared Household money.</p></Reveal><div className="screenshot-grid">{screenshots.map(([src, title, description], index) => <Reveal className={`screenshot-card screenshot-card--${index + 1}`} key={src}><a href={`#screen-${index + 1}`}><div className="screenshot-frame"><img src={src} alt={`WalletTrails ${title} screen`} loading="lazy" /></div><div className="screenshot-caption"><span><small>WALLETTRAILS APP</small><b>{title}</b><p>{description}</p></span><i aria-hidden="true">↗</i></div></a></Reveal>)}</div><p className="screenshots-note">Tap a screen to view it in full detail.</p></div>{screenshots.map(([src, title], index) => <div className="screenshot-lightbox" id={`screen-${index + 1}`} key={`screen-${index + 1}`}><a className="lightbox-close" href="#screenshots" aria-label="Close screenshot preview">×</a><a className="lightbox-backdrop" href="#screenshots" aria-label="Close screenshot preview" /><div><img src={src} alt={`WalletTrails ${title} screen`} /><p>{title} <span>WalletTrails for Android</span></p></div></div>)}</section>
}

function UseCases() {
  return <section className="use-cases"><div className="shell"><Reveal className="heading center"><span className="eyebrow">Made for everyday life</span><h2>One calm place for the<br /><em>ways you manage money.</em></h2><p>WalletTrails is shaped around practical moments, not complicated finance jargon.</p></Reveal><div className="case-grid"><Reveal className="case-card"><span className="case-icon solo">⌂</span><small>FOR YOU</small><h3>Keep everyday money in view.</h3><p>See cash and bank wallets together, log spending in a few taps, and understand where your month is going.</p><ul><li>Total balance across your wallets</li><li>Quick income, expense, and transfer entry</li><li>Private amount masking when needed</li></ul></Reveal><Reveal className="case-card"><span className="case-icon work">↗</span><small>FOR YOUR WORK</small><h3>Make client income easier to follow.</h3><p>Track monthly retainers, one-time jobs, advances, and payment plans without losing sight of what remains.</p><ul><li>Recurring and one-time income sources</li><li>Record received payments as they happen</li><li>Forecast the month ahead</li></ul></Reveal><Reveal className="case-card"><span className="case-icon home">♧</span><small>FOR YOUR PEOPLE</small><h3>Share costs without sharing everything.</h3><p>Create a Household for a home, event, or trip while each member keeps their own private money private.</p><ul><li>Invite by code or secure link</li><li>Ongoing or closeable event ledgers</li><li>Equal-split suggestions for the group</li></ul></Reveal></div></div></section>
}

const faqs = [
  ['Can I use WalletTrails without an internet connection?', 'Yes. Personal wallets and recent transactions can be available from your local cache, and personal income, expense, and transfer entries can be queued offline. They sync when your device is online again. Shared Household changes intentionally need an internet connection.'],
  ['Can other Household members see my bank balance?', 'No. Household members see only entries added to the shared Household ledger, including who paid a shared item. Your personal wallets, income, loans, and unrelated transactions stay private to your account.'],
  ['What can WalletTrails remind me about?', 'You can set reminders around monthly costs, loans, installments, and money you expect to receive. Reminder lead times can include three days before, one day before, and the due day.'],
  ['How does WalletTrails protect amounts on a shared or public phone?', 'You can hide values across the app and reveal them with your device biometrics or your WalletTrails PIN. The app remains usable while values are masked, and it can re-hide values after you leave the app.'],
  ['Does WalletTrails connect to my bank automatically?', 'WalletTrails lets you track bank and cash wallets inside the app. It does not promise automatic bank feeds; you add or import your own financial activity.'],
  ['Can I export my information?', 'WalletTrails supports CSV sharing for personal and Household reports. The web experience also supports report export options, giving you a useful copy when you need it.'],
]
function FAQSection() {
  return <section className="faqs" id="faqs"><div className="shell"><Reveal className="heading center"><span className="eyebrow">Helpful answers</span><h2>Questions, answered<br /><em>without the jargon.</em></h2></Reveal><Reveal className="faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>{question}</span><i>+</i></summary><p>{answer}</p></details>)}</Reveal></div></section>
}

function SupportSection() {
  return <section className="support" id="support"><div className="shell support-grid"><Reveal className="support-copy"><span className="eyebrow">Help & support</span><h2>A little help goes<br />a <em>long way.</em></h2><p>Whether you are getting started, managing a reminder, or have a question about your account, WalletTrails includes Help & Support inside the app.</p><a href="#download" className="button">Get WalletTrails <Icon name="arrow" size={17} /></a></Reveal><Reveal className="support-panel"><article><span className="support-icon">?</span><div><small>GETTING STARTED</small><h3>New to WalletTrails?</h3><p>Begin with your wallets, then record your first income or expense. The app is built for small, useful steps.</p></div></article><article><span className="support-icon">⌁</span><div><small>IN-APP SUPPORT</small><h3>Need a hand?</h3><p>Open Settings, then Help & Support to send a ticket directly from WalletTrails.</p></div></article><article><span className="support-icon">♙</span><div><small>ACCOUNT & PRIVACY</small><h3>Stay in control.</h3><p>Use your app settings to manage amount privacy, reminders, themes, and account requests.</p></div></article></Reveal></div></section>
}

function App() {
  const [menu, setMenu] = useState(false)
  const [tour, setTour] = useState(false)
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('visible')), { threshold: 0.12 }); document.querySelectorAll('.reveal').forEach((item) => observer.observe(item)); return () => observer.disconnect() }, [])
  useEffect(() => { document.body.style.overflow = tour ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [tour])
  return <><Header menu={menu} setMenu={setMenu} /><main>
    <section className="hero" id="home"><div className="shell hero-grid"><Reveal className="hero-copy"><span className="eyebrow"><i />A calmer way to manage money</span><h1>Follow every <em>rupee.</em><br />Feel more <span>free.</span></h1><p>WalletTrails brings your spending, wallets, bills, and shared expenses together in one thoughtful place.</p><div className="hero-actions"><a className="button" href="#download">Start tracking free <Icon name="arrow" size={17} /></a><button className="watch" onClick={() => setTour(true)}><span><Icon name="play" size={12} /></span>See how it works</button></div><div className="human-note"><div><i>H</i><i>S</i><i>M</i></div>Made for real life, not spreadsheets</div></Reveal><Reveal className="hero-visual"><div className="orb one" /><div className="orb two" /><PhonePreview /><div className="float spent"><span>↘</span><p><small>Spent this week</small><b>Rs. 14,850</b></p><strong>−12%</strong></div><div className="float budget"><span>✓</span><p><small>Budget</small><b>On track</b></p></div></Reveal></div></section>
    <section className="trust"><div className="shell"><p>ONE SIMPLE HOME FOR THE FINANCIAL THINGS THAT MATTER</p><div><span>Personal money</span><i /><span>Shared living</span><i /><span>Future goals</span><i /><span>Daily clarity</span></div></div></section>
    <section className="showcase" id="preview"><div className="shell"><Reveal className="heading center"><span className="eyebrow">A look inside</span><h2>Clear money moments,<br /><em>beautifully connected.</em></h2><p>From a quick expense to your monthly picture, every detail is designed to feel simple and human.</p></Reveal><div className="showcase-grid"><Reveal className="overview"><header><span>◔</span><p><small>Monthly overview</small><b>September 2026</b></p><i>•••</i></header><div className="total"><small>You have spent</small><b>Rs. 42,780</b><span>of Rs. 55,000 planned</span></div><div className="donut-content"><div className="donut"><span><b>78%</b><small>used</small></span></div><div>{[['Food & dining', 'Rs. 15,200', 'blue'], ['Home & bills', 'Rs. 12,500', 'purple'], ['Travel', 'Rs. 6,750', 'orange'], ['Other', 'Rs. 8,330', 'gray']].map(([label, amount, tone]) => <p className="legend" key={label}><i className={tone} />{label}<b>{amount}</b></p>)}</div></div><footer>Spending by category <a>See details →</a></footer></Reveal><Reveal className="tour-card"><div className="tour-art"><div /><button onClick={() => setTour(true)} aria-label="Play product tour"><Icon name="play" size={18} /></button><span>01:00</span></div><article><small>PRODUCT TOUR</small><h3>Your day, in one minute.</h3><p>See how WalletTrails helps you capture expenses, pay bills, and stay on course.</p><button onClick={() => setTour(true)}>Play video →</button></article></Reveal><Reveal className="quick-card"><span className="ficon purple">⇄</span><small>MOVE MONEY EASILY</small><h3>Transfers that stay in sync.</h3><p>Shift funds between cash and bank accounts without confusing your budget.</p><div>Cash <i>→</i> Bank</div></Reveal><Reveal className="people-card"><span className="people"><i>H</i><i>S</i><i>M</i></span><small>SHARED SPENDING</small><h3>Fairness without the maths.</h3><p>Split household expenses and keep everyone in the loop.</p><a href="#features">↗</a></Reveal></div></div></section>
    <section className="features shell" id="features"><Reveal className="heading split"><div><span className="eyebrow">Everything in reach</span><h2>Less money stress.<br /><em>More clarity.</em></h2></div><p>Helpful tools for understanding each rupee—without making personal finance feel like work.</p></Reveal><div className="feature-grid">{productFeatures.map(([icon, title, text, tone], index) => <Reveal className="feature" key={title}><span className={`ficon ${tone}`}><Icon name={icon} size={21} /></span><i>{String(index + 1).padStart(2, '0')}</i><h3>{title}</h3><p>{text}</p></Reveal>)}</div></section>
    <ProductDepth />
    <UseCases />
    <ScreenshotGallery />
    <FAQSection />
    <SupportSection />
    <section className="about about--story" id="about"><div className="shell about-grid"><Reveal className="about-art about-art--screens"><div className="about-orb" /><div className="about-dots" /><div className="about-screen about-screen--back"><img src="/media/screenshots/household.png" alt="WalletTrails Household shared expense screen" /></div><div className="about-screen about-screen--main"><img src="/media/screenshots/reports.png" alt="WalletTrails monthly reports screen" /></div><div className="about-rating"><span>✦</span> Private by design</div><div className="about-note">Personal money stays private.<br /><b>Shared expenses stay clear.</b></div></Reveal><Reveal className="about-copy"><span className="eyebrow">About WalletTrails</span><h2>Clear money,<br />for <em>real life.</em></h2><p>WalletTrails is a Pakistan-first money companion for the everyday decisions behind your cash, bank wallets, income, bills, and future plans. It replaces scattered notes and stressful guesswork with one calm, useful picture.</p><p>Built for salaried people, freelancers, families, and roommates, it helps you follow every rupee without turning personal finance into a spreadsheet project.</p><div className="about-promises"><span><i>✓</i> Personal wallets stay personal</span><span><i>✓</i> Track money even when you are offline</span><span><i>✓</i> Share Household costs without sharing everything</span></div><a href="#how">See how WalletTrails works <Icon name="arrow" size={16} /></a></Reveal></div></section>
    <section className="how" id="how"><div className="shell"><Reveal className="heading center"><span className="eyebrow">Simple from the start</span><h2>How it <em>works.</em></h2><p>Start with the money you already have, capture the moments that matter, and let WalletTrails make the month easier to understand.</p></Reveal><div className="how-flow">{[["↓", 'Get WalletTrails', 'Download the Android app and create your private WalletTrails account. Your money starts with you.'], ['♙', 'Add your wallets', 'Add your cash and bank wallets with their opening balances. You will see one clear total straight away.'], ['✓', 'Follow every rupee', 'Log income, expenses, and transfers. Use reports, reminders, privacy lock, and Household only when you need them.']].map(([symbol, title, body], index) => <Reveal className="how-step" key={title}><span className={`how-step__icon how-step__icon--${index + 1}`}>{symbol}</span><span className="how-step__number">0{index + 1}</span><h3>{title}</h3><p>{body}</p>{index < 2 && <i className="how-connector" aria-hidden="true">···</i>}</Reveal>)}</div><Reveal className="how-callout"><span>✦</span><p><b>Start small.</b> Add one wallet and log your first expense today. The clearer picture follows naturally.</p><a href="#download">Get the app <Icon name="arrow" size={16} /></a></Reveal></div></section>
    <section className="download shell" id="download"><Reveal><span className="eyebrow light">Ready when you are</span><h2>Start following<br />every <em>rupee.</em></h2><p>Take the first small step towards feeling more at ease with your money.</p><div className="dl-actions"><a className="playstore" href="#home"><i>▶</i><span><small>GET IT ON</small><b>Google Play</b></span></a><a className="button white" href="#home">Explore WalletTrails <Icon name="arrow" size={16} /></a></div></Reveal><div className="mini-phone"><i /><p>WalletTrails</p><article><small>Available balance</small><b>Rs. 86,420</b></article><span /><span /><span /><strong>+</strong></div></section>
  </main><footer><div className="shell foot-main"><Logo inverse /><p>Follow every rupee. Feel more free.</p><nav><a href="#features">Features</a><a href="#about">About</a><a href="#how">How it works</a><a href="/privacy.html">Privacy</a></nav></div><div className="shell foot-bottom"><span>© 2026 WalletTrails. Made for everyday money.</span><a href="#home">Back to top ↑</a></div></footer>{tour && <TourModal onClose={() => setTour(false)} />}</>
}
function TourModal({ onClose }) { return <div className="modal" role="dialog" aria-modal="true" aria-label="WalletTrails product tour"><button className="backdrop" onClick={onClose} aria-label="Close tour" /><article><button className="x" onClick={onClose} aria-label="Close"><Icon name="close" /></button><Logo inverse /><small>PRODUCT TOUR · 01:00</small><div><span><Icon name="plus" size={30} /></span><h2>Track it as it happens.</h2><p>Every expense, income, and transfer has a place.</p></div><nav><i /><i /><i /></nav></article></div> }
export default App
