import { StrictMode, useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './privacy.css'
import './brand.css'

const Logo = () => <a className="logo logo--inverse" href="/"><img src="/media/wallettrail-logo.png" alt="WalletTrails" /><span>Wallet<span>Trails</span></span></a>
const sections = [
  ['1. What this policy covers', <p>This policy explains how WalletTrails handles information when you use our Android app, website, and support channels. WalletTrails is a personal money-management app built for people tracking wallets, spending, income, bills, reminders, reports, and optional household expenses.</p>],
  ['2. Information you provide', <><p>To create and use an account, you may provide account information such as your name, email address, and password. You may also choose to add financial records inside the app, including wallet names, balances, transactions, income, recurring costs, bills, loans, receivables, categories, notes, and report settings.</p><p>If you create or join a Household, you may provide a household name, shared-ledger entries, an invite code or invite link, and shared-expense details. Household information is visible only to members of that Household according to the access controls in the product.</p></>],
  ['3. How we use information', <><p>We use information to provide the service you request: sign you in, save and synchronize your records, calculate balances and forecasts, show reports, deliver reminder notifications, respond to support requests, and keep the app secure.</p><p>We may also use limited, non-sensitive product signals to understand whether features work well, diagnose errors, and improve WalletTrails. We do not use your personal financial records to target advertising or sell them to advertisers.</p></>],
  ['4. Personal money and Household privacy', <><p>Your personal wallets, income, loans, and personal transactions are private to your account. Joining a Household does not give other members access to those private records.</p><p>Household members can see the information deliberately added to that Household’s shared ledger—such as a shared expense, the member who paid it, contributions, and settlement suggestions. WalletTrails does not move money between members’ bank accounts; split results are suggestions for your group.</p></>],
  ['5. Device permissions and sensitive features', <><p>WalletTrails may ask for notification permission so it can send due-date reminders and support-related alerts. You can control notifications through device and app settings.</p><p>The optional privacy lock uses your device’s biometric or device-credential system to reveal amounts. Biometric data is handled by your device operating system; WalletTrails does not receive or store your fingerprint or face template. The app can also mask amounts on screen and may re-hide them after the app moves to the background.</p></>],
  ['6. Offline storage and synchronization', <><p>WalletTrails can cache recent personal records on your device so you can continue to view information and add personal transactions when you are offline. Transactions created offline are queued for synchronization when a connection becomes available.</p><p>For data integrity and privacy, shared Household changes may require an internet connection. Signing out is designed to clear the local offline database for that account from the device.</p></>],
  ['7. Notifications', <p>Reminder notifications can be scheduled locally on your device or delivered through our notification infrastructure when enabled. When amount privacy is active, notification copy is designed not to expose exact PKR values. You can turn notification permissions off in your device settings at any time.</p>],
  ['8. Analytics and diagnostics', <><p>WalletTrails may use privacy-conscious analytics to understand product flows, such as whether a user created a wallet, used an offline queue, joined a Household, or exported a report. We aim to avoid sending raw transaction amounts, full notes, wallet balances, account numbers, or invite codes as analytics events.</p><p>Where session diagnostics are used, finance inputs and money-value elements are configured to be masked. Analytics helps us improve the product; it is not the financial source of truth and is not used to profile your spending.</p></>],
  ['9. Advertising and premium features', <p>WalletTrails may offer an ad-supported free experience and optional premium features in the future. If advertising is enabled, it will be controlled through app configuration and should not appear over balance values, PIN or biometric screens, or money-entry confirmations. Premium users may receive an ad-free experience. Any advertising-related data practices will be described in the app’s Play Data Safety disclosure and updated here when applicable.</p>],
  ['10. Sharing and service providers', <p>We share information only as needed to operate WalletTrails—for example, with hosting, database, authentication, notification, analytics, crash-diagnostics, or customer-support providers acting on our behalf. We do not sell personal financial records. We do not give WalletTrails staff routine access to your transactions, balances, bills, or Household ledger lines for product operations; administrative tools are designed around safe account and aggregate information instead.</p>],
  ['11. Data retention, deletion, and your choices', <p>We retain account and financial data while your account is active and as needed to provide the service, meet legal obligations, resolve disputes, and prevent abuse. You can update certain account settings in the app. To request account deletion or ask a privacy question, use the in-app Help & Support channel and select the account or deletion category. We will handle verified requests in accordance with applicable law and our operational requirements.</p>],
  ['12. Security', <p>We use reasonable technical and organizational safeguards appropriate for a personal finance app, including authenticated access, encrypted transport where supported, access controls, and privacy-focused product design. No internet or storage system is completely secure, so please use a unique password and keep your device protected.</p>],
  ['13. Children', <p>WalletTrails is not intended for children. Do not use WalletTrails or provide personal information if you are below the minimum age required to consent to data processing where you live.</p>],
  ['14. Changes to this policy', <p>We may update this policy as WalletTrails changes—for example, when we add new integrations, payment options, or data features. We will update the “Last updated” date and, where required, provide additional notice in the app.</p>],
]

function PrivacyPage() {
  useEffect(() => { document.title = 'Privacy Policy — WalletTrails' }, [])
  return <><header className="privacy-header"><div className="privacy-shell"><Logo /><a href="/" className="privacy-back">← Back to WalletTrails</a></div></header><main className="privacy-main"><div className="privacy-shell"><div className="privacy-hero"><span>LEGAL & PRIVACY</span><h1>Your money story is<br /><em>your business.</em></h1><p>We built WalletTrails around a simple principle: clearer money should never mean less privacy.</p><small>Last updated: 11 September 2026</small></div><div className="privacy-layout"><aside><b>ON THIS PAGE</b>{sections.map(([title], index) => <a href={`#policy-${index + 1}`} key={title}>{title.replace(/^\d+\. /, '')}</a>)}</aside><article className="policy-copy"><div className="policy-summary"><strong>In short</strong><p>WalletTrails helps you manage your money. Your private money records stay private, Household members see only what you intentionally share, and we do not sell your financial records.</p></div>{sections.map(([title, content], index) => <section id={`policy-${index + 1}`} key={title}><h2>{title}</h2>{content}</section>)}</article></div></div></main><footer className="privacy-footer"><div className="privacy-shell"><Logo /><span>© 2026 WalletTrails. Follow every rupee.</span><a href="/">Home</a></div></footer></>
}
createRoot(document.getElementById('root')).render(<StrictMode><PrivacyPage /></StrictMode>)
